poll_time: 300

telegram:
    token: "putHereYourToken"
    chat_id: 123456
    keywords:
        ignore: "IGNORE"
        ask_again_and_reload: "ASKAGAINRELOAD"
        ask_again: "ASKAGAIN"

abn:
    iban_account: "NLXXABNA0xxxxx"
    pass_number: 123
    soft_token: "12345"

gsheet:
    id: "gsheet_ID"
    expenses_range: "Uitgaven!A2:D"
    income_range: "Inkomsten!A2:D"
    date_format: "%d-%m-%Y %H:%M:%S"
    use_comma: true

    order_of_values:
        - timestamp
        - description
        - category
        - amount

expense_categories:
        -   - Boodschappen:
                short_name: "ğŸ›/ ğŸ"
            - Electronica:
                short_name: "ğŸ’»"
            - Kleding:
                short_name: "ğŸ‘•"

        -   - Kantoorspulletjes:
                short_name: "ğŸ““/ ğŸ–¨"
            - Persoonlijke verzorging:
                short_name: "ğŸ›€ğŸ¤³"
            - Cadeaus:
                short_name: "ğŸ"
            - Zorg:
                short_name: "ğŸ¥"

        -   - Uitjes:
                short_name: "ğŸ¡"
            - Reizen:
                short_name: "ğŸš…"

        -   - Overig
            - Investeringen:
                  short_name: "ğŸ“ˆ"

income_categories:
        -   - Werk:
                short_name: "ğŸ¢ğŸ’¸"
            -  Belastingd. toeslagen:
                short_name: "ğŸ‡³ğŸ‡±ğŸ’¸"